target:
	#g++ ./split.cpp /www/web/default/nlp-lib/libNLPIR.so -lpthread -Wall -Wunused -O3 -DOS_LINUX 
	g++ ./*.cpp ./*.h  /www/web/default/info_extract/libNLPIR.so  -std=c++11 -lpthread -w  -O3 -DOS_LINUX 
	#g++ extract.cpp extract.h /www/web/default/nlp-lib/libDocExtractor.so -Wall -Wunused -O3 -DOS_LINUX
clean:
	rm a.out
