target:
	#g++ ./split.cpp /www/web/default/nlp-lib/libNLPIR.so -lpthread -Wall -Wunused -O3 -DOS_LINUX 
	g++ ./split.cpp ./jsoncpp.cpp /www/web/default/nlp-lib/libNLPIR.so /www/web/default/nlp-lib/libDocExtractor.so  -lpthread -w  -O3 -DOS_LINUX 
	#g++ extract.cpp /www/web/default/nlp-lib/libDocExtractor.so -Wall -Wunused -O3 -DOS_LINUX
clean:
	rm a.out
